/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.inveno.hotoday.common.thrift.color;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ab_status implements org.apache.thrift.TEnum {
  RC_STATUS_OK(0),
  RC_SERVER_ERROR(1),
  RC_SERVER_FAULT(2),
  RC_UNKNOW_ERROR(3);

  private final int value;

  private ab_status(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ab_status findByValue(int value) { 
    switch (value) {
      case 0:
        return RC_STATUS_OK;
      case 1:
        return RC_SERVER_ERROR;
      case 2:
        return RC_SERVER_FAULT;
      case 3:
        return RC_UNKNOW_ERROR;
      default:
        return null;
    }
  }
}
